spring.application.name=authorization-server

logging.level.org.springframework.security=TRACE
logging.level.org.springframework.security.oauth2=TRACE
logging.level.org.springframework.security.oauth2.server.authorization=TRACE