spring.application.name=authorization-server

authorization.server.issuer=http://localhost:8080

logging.level.org.springframework.security=TRACE
logging.level.org.springframework.security.oauth2=TRACE
logging.level.org.springframework.security.oauth2.server.authorization=TRACE